### ISSUE TITLE
Pre-built plans made by fitness experts

### ISSUE THREAD

**Issue by serrq** [Iamlooker/Kenko#13]
I would like having at least 10-12 pre-built plans based on fitness targets.

For example: build muscles, loss fats, increase stamina, etc. 

Also possible setting multiple targets at once (plans' filters).

**Comment by Iamlooker** [comment]
I cannot afford to hire a fitness expert. But I am pretty scientific and good at resistance training.

I will add more prebuilt plans in future made by me. But Hiring someone is out of scope for now
