### ISSUE TITLE
Are negative weight and reps a bug or a wanted behavior?

### ISSUE THREAD

**Issue by serrq** [Iamlooker/Kenko#15]
![1000111790](https://github.com/Iamlooker/Kenko/assets/113377431/3f257b5b-b066-4cf9-b02e-b8087fedab62)

**Comment by Iamlooker** [comment]
Do you train at home?

**Comment by Iamlooker** [comment]
Aah, the app is not necessarily built for calisthenics but I think you can still use it for simple tracking purposes.

I will be adding info about different stuffs in the app like:
- How to get out of strength plateaus
- What are common scientific ways of training
- What are some scientific terms which are useful
- How to train for size or strength
- And more as we progress

**Comment by Iamlooker** [comment]
I will think about it, but I dont promise it, as I am targeting lifters who go to gym and this app is basically my journal for my self. And I think you know, I alone cannot master everything so I will be targeting and improving what I will be using and will think about other thinks later

**Comment by Iamlooker** [comment]
Yes, it would be great. But the app is designed to shit on organizations which provide similar experience (there apps are obviously better than this) for a load of money, or with loads of ads.

I know there are some really good apps which are paid like RP Hypertrophy App and the Jeff Nippard app. And I cannot compete with them at all as they are PHd holders and also really really experienced and smart people unlike me. I get inspirations on how to train from them.

**Comment by Iamlooker** [comment]
I suggest following Renaissance Periodization, Jeff Nippard, Menno Henselmans, Milo Wolf for best and up to date science based training. They also have some Home Workout videos which can help you progress.

Disclaimer: the host of Renaissance Periodization, i.e. Dr. Mike Israetel, make some NSFW jokes and his humor is rather sarcastic, so only follow them if you can take those.

**Comment by Iamlooker** [comment]
Negative reps have been fixed but weight is like an assistance, so I will keep it.
