### ISSUE TITLE
Two current plans at once

### ISSUE THREAD

**Issue by serrq** [Iamlooker/Kenko#19]
Helpful when an user wants mix aerobic and weighted workouts in the same week or day.

Example:

Mo Tu Th Fr  --> weighted (dumbbells)
We Sa            --> running
Su                   --> rest

![1000111806](https://github.com/Iamlooker/Kenko/assets/113377431/6eae420c-0fd7-419c-8d80-3910f5d503c8)

**Comment by Iamlooker** [comment]
Cardio is not supported for now. If I ever add support for it, it will we available on demand instead of plan.

I do plan to include cardio in my plan too, but I need to think about how I would do it
