### ISSUE TITLE
Exercise name typo

### ISSUE THREAD

**Issue by ArvindEXE** [Iamlooker/Kenko#2]
I noticed a typo in the exercise selection, see below:

"Tircep Push Down"

![Screenshot_20240513-005126](https://github.com/Iamlooker/Kenko/assets/84917151/408c8fa8-3425-402d-a93f-68d42af736c2)

Thank you for making this, I think found the perfect workout log for me :)

**Comment by Iamlooker** [comment]
For now you can edit this your self, will fix it in next update

**Comment by Iamlooker** [comment]
Should be fixed for new users
