### ISSUE TITLE
Mistakenly I deleted two exercises due the sliding action

### ISSUE THREAD

**Issue by serrq** [Iamlooker/Kenko#25]
In the future please adding a trash bin (4 weeks auto delete) to quickly restoring mistakenly deleted exercises.

**Comment by noahgitsham** [comment]
> In the future please adding a trash bin
And/or a confirmation on delete

**Comment by Iamlooker** [comment]
> And/or a confirmation on delete
> 
Will be added in next update

**Comment by Iamlooker** [comment]
It would be unnecessary to add a trash bin. Lets say a user deletes a exercise by choice, they will surely know wgat that exercise was and then can simple add it backs, its just a name. And if they didn't what they deleted but it was deleted deliberately then it doesn't make a difference, as they can add exercises they want.

I will add a confirmation in next release

**Comment by Iamlooker** [comment]
Fixed with b7c5a5b
