### ISSUE TITLE
Cannot reaching the "Save" button while create a new exercise

### ISSUE THREAD

**Issue by serrq** [Iamlooker/Kenko#26]
Kenko 1.2.0
Android 14
OnePlus CPH2399

![1000113427](https://github.com/Iamlooker/Kenko/assets/113377431/2830bfdf-9bdd-4260-9e47-229891381a23)

**Comment by Iamlooker** [comment]
They do target but not enough to grow the muscle, they are primarily back exercise

**Comment by Iamlooker** [comment]
Almost all sources suggest chest but thats a false positive
