### ISSUE TITLE
Add confirmation when backing out of unsaved plan

### ISSUE THREAD

**Issue by noahgitsham** [Iamlooker/Kenko#28]
When backing out of a modified plan, if you have not saved, your changes will be immediately deleted. An "Are you sure you want to quit (yes/no)" or "You have unsaved changes(Save and exit/Discard changes)" pop-up would be nice

**Comment by Iamlooker** [comment]
Thoughts on autosave all changes?

**Comment by noahgitsham** [comment]
If you want to do autosave, I think you should still have to choose to commit to the changes. Backing out of uncommit changes should prompt for Save/Discard changes, and if the app closes with uncommit changes, reopening it should bringing you back to these uncommit changes.

**Comment by Iamlooker** [comment]
This is excessive, I was thinking about removing save button and just directly commiting the changes. If it ia not very desirable than I will just add a confirmation dialog on unsaved changes

**Comment by noahgitsham** [comment]
Fair enough. I can see myself making changes before deciding I actually don't want them, but I suppose there's not a huge amount that I would be changing at once, so not a big deal.
