### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by saltsoftdrink** [Iamlooker/Kenko#3]
How to add monochrome icon

**Comment by Iamlooker** [comment]
If you want to do it yourself then do the following:

1. Duplicate [this](https://github.com/Iamlooker/Kenko/blob/main/app/src/main/res/drawable/ic_launcher_foreground.xml) file and rename the new file to `ic_launcher_foreground`
2. Remove [this tag](https://github.com/Iamlooker/Kenko/blob/c102166f868c5acd81a1cd053cff83ce55389508/app/src/main/res/drawable/ic_launcher_foreground.xml#L14)
3. Add fill color like [this](https://github.com/Droid-ify/client/blob/main/app/src/main/res/drawable/ic_launcher_monochrome.xml#L13)
4. Add the following tags to `ic_launcher.xml`
![image](https://github.com/Iamlooker/Kenko/assets/60404093/2c8f14e9-9e00-4fd4-aa62-7a8fdf0d94ec)

**Comment by Iamlooker** [comment]
If you are not working on this, I will finish this
