### ISSUE TITLE
Can't delete or modify sets while doing a workout

### ISSUE THREAD

**Issue by silvzr** [Iamlooker/Kenko#4]
![Screenshot_20240515-103903_Kenko.png](https://github.com/Iamlooker/Kenko/assets/117378129/8b735889-5d45-452d-a54d-80adb1ef715c)

if someone incorrectly adds the wrong number of reps and weight he's not able to modify it later or delete the set itself

**Comment by Iamlooker** [comment]
Was fixed in last updated
