### ISSUE TITLE
'time' field missing from 'Set' object in JSON data

### ISSUE THREAD

**Issue by hyperionhex** [Iamlooker/Kenko#7]
I've implemented the UI changes to include the time in the SetItem. However, upon running the application and clicking on the "start" button, it terminates the app.

![time](https://github.com/Iamlooker/Kenko/assets/96485995/9f4d6052-602f-4dc3-aa78-0f1934ce453f)

> FATAL EXCEPTION: main Process: com.looker.kenko.debug,  PID: 11829 kotlinx.serialization. MissingFieldException:  Field 'time' is required for type with serial name 'com.looker.kenko.data. model. Set' ,  but it was missing at path: $[0] at kotlinx.serialization. json. internal. StreamingJsonDecoder. decodeSerializableValue( StreamingJsonDecoder. kt: 95)  at kotlinx.serialization. encoding. AbstractDecoder. decodeSerializableValue( AbstractDecoder. kt: 43)  with tag AndroidRuntime

**Comment by Iamlooker** [comment]
There is no time field, its either repetitions or duration, which I think is the right way to do it

I mean there can only be one at a time, either reps or duration

**Comment by Iamlooker** [comment]
I have implemented this

I will add a timer in future
